<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KuZob4P' shared service.

return $this->privates['.service_locator.KuZob4P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ProductsController::modifyProducts' => ['privates', '.service_locator.d8oDogK', 'get_ServiceLocator_D8oDogKService.php', true],
    'App\\Controller\\ProductsController::showProducts' => ['privates', '.service_locator.d8oDogK', 'get_ServiceLocator_D8oDogKService.php', true],
    'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.rUpeG.j', 'get_ServiceLocator_RUpeG_JService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController::resetPassword' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
    'App\\Controller\\ProductsController:modifyProducts' => ['privates', '.service_locator.d8oDogK', 'get_ServiceLocator_D8oDogKService.php', true],
    'App\\Controller\\ProductsController:showProducts' => ['privates', '.service_locator.d8oDogK', 'get_ServiceLocator_D8oDogKService.php', true],
    'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.rUpeG.j', 'get_ServiceLocator_RUpeG_JService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController:resetPassword' => ['privates', '.service_locator.lm3AYgL', 'get_ServiceLocator_Lm3AYgLService.php', true],
], [
    'App\\Controller\\ProductsController::modifyProducts' => '?',
    'App\\Controller\\ProductsController::showProducts' => '?',
    'App\\Controller\\SecurityController::forgottenPassword' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\SecurityController::resetPassword' => '?',
    'App\\Controller\\ProductsController:modifyProducts' => '?',
    'App\\Controller\\ProductsController:showProducts' => '?',
    'App\\Controller\\SecurityController:forgottenPassword' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\SecurityController:resetPassword' => '?',
]);
