<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.d8oDogK' shared service.

return $this->privates['.service_locator.d8oDogK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'productsRepository' => ['privates', 'App\\Repository\\ProductsRepository', 'getProductsRepositoryService.php', true],
], [
    'productsRepository' => 'App\\Repository\\ProductsRepository',
]);
